### ISSUE TITLE
Coupon redeem button is disabled for expired coupons

### ISSUE THREAD

**Issue by dmaddock1** [emptysetsquad/dollar-dashboard#24]
The coupon redeem button remains disabled as long as the DAO redeemable pool is empty. However, since EIP-16 expired coupons can be redeemed after expiry for their principal even if the DAO does not have any redeemable funds.

The Redeem button should be enabled if a coupon is expired.

**Comment by dguess** [comment]
@dmaddock1 As mentioned in the pull request this fix doesn't seem to work?

**Comment by dmaddock1** [comment]
Yup, you are right. Just pushed the missing piece a minute ago.

**Comment by dmaddock1** [comment]
I tried to get in touch on discord but might have messaged the wrong guy...

**Comment by dguess** [comment]
thanks @dmaddock1 looks good now 👍
